test
mim3009/circleci pull request #1
Opened 2018-12-22 07:27 UTC by mim3009

2018-12-22 08:13 UTC, mim3009 commented on README.md
> -# circleci test
another test comment

2018-12-22 08:27 UTC, mim3009 commented
arr

2018-12-22 08:40 UTC, mim3009 commented on README.md
> -# circleci test
fffftest

2018-12-22 08:41 UTC, mim3009 commented on README.md
> -# circleci test
fffftest

2018-12-24 12:33 UTC, mim3009 commented on README.md
> +# circleci
done

2018-12-24 18:42 UTC, mim3009 commented on README.md
> -# circleci test
newTest

2018-12-24 19:09 UTC, mim3009 commented
red

2018-12-24 19:10 UTC, mim3009 commented on README.md
> \ No newline at end of file
red2

2018-12-24 19:11 UTC, mim3009 commented
red3

2018-12-25 09:42 UTC, mim3009 commented
red4

2018-12-25 09:53 UTC, mim3009 commented on README.md
> -# circleci test
tess

2019-01-02 07:48 UTC, 308255 submitted a review, later dismissed

2019-01-02 08:38 UTC, IvankoRambo commented
I disapprove this PR

2019-01-02 08:40 UTC, 308255 requested changes

2019-01-02 08:40 UTC, IvankoRambo commented on README.md
> +# circleci
It should circle not circleci

2019-01-02 08:41 UTC, 308255 submitted a review, later dismissed

2019-01-02 08:41 UTC, 308255 requested changes

2019-01-02 08:41 UTC, IvankoRambo commented on README.md
> +# circleci
Test comment

2019-01-02 08:42 UTC, 308255 submitted a review, later dismissed

2019-01-02 08:48 UTC, 308255 submitted a review, later dismissed

2019-01-02 08:49 UTC, 308255 submitted a review, later dismissed

2019-01-02 09:03 UTC, 308255 submitted a review, later dismissed

2019-01-02 09:11 UTC, 308255 submitted a review, later dismissed

2019-01-02 09:42 UTC, RedHunger commented on README.md
> +# circleci
Another test comment

2019-01-02 10:03 UTC, 308255 submitted a review, later dismissed

2019-01-02 10:42 UTC, 308255 approved these changes

2019-01-02 10:43 UTC, 308255 approved these changes

2019-01-02 11:19 UTC, 308255 approved these changes

2019-01-02 12:13 UTC, merged